---
type: map
mapping:
  listen:
    type: str
  pool:
    type: map
    mapping:
      workers:
        type: int
      mode:
        enum:
          - inproc
          - fork
          - detach
        type: str
  projects:
    required: 1
    type: seq
    sequence:
    - mapping:
        id:
          type: str
        webhooks:
          type: seq
          sequence:
          - type: map
            mapping:
              id:
                type: str
                required: 1
              cgi:
                type: str
                required: 1
        build:
          type: seq
          sequence:
          - type: str
        post:
          type: seq
          sequence:
          - type: str
      type: map
  workers:
    type: map
    mapping:
      language:
        type: int
      stopwaitsecs:
        type: int
